### PR TITLE
Add workflow to trigger farmOS.org Netlify builds when posts are added

### LINKED ISSUE #4: Add workflow to trigger farmOS.org Netlify builds when posts are added
See:
- https://github.com/farmOS/farmOS/pull/456
- Latest file https://github.com/farmOS/farmOS/blob/2.x/.github/workflows/netlify-build-docs.yml

### PR DESCRIPTION
**Pull request by mstenta**
Fixes #4

### CODE REVIEW

**Review by paul121 — DISMISSED** [review]

**Review by jgaehring — CHANGES_REQUESTED** [review]
Hmm, I want to approve the changes here in this one commit, but I see that the video blog post was already merged into main, and merging this will trigger that post to be deployed on farmos.org. Was that intentional, or is that post complete? To my mind, there should at least be some kind of description, for accessibility if nothing else.

I know it's out of scope for this PR, but given the nature of this PR will have side effects in production, would you be open to accepting an additional commit to add a description if I added it?

**Comment by mstenta** [comment]
> I see that the video blog post was already merged into main, and merging this will trigger that post to be deployed on farmos.org. Was that intentional, or is that post complete?

Oh oops! I misinterpreted your "DO IT NOW!!" Arnold meme in chat as approval to publish. 😆

https://irc.farmos.org/bot/log/farmOS/2022-11-10#T84550

> would you be open to accepting an additional commit to add a description if I added it?

Sure! You're right it should have some kind of text for accessibility purposes at the very least. (Transcriptions would be next level!)

This is the description I used on the YouTube video itself, if we want to just reuse that:

> A very quick overview of farmOS, what it can be used for, and where we are headed as a community.

**Comment by jgaehring** [comment]
> Oh oops! I misinterpreted your "DO IT NOW!!" Arnold meme in chat as approval to publish.

Ah, sorry, heat of the moment. Admit I didn't really look into it.

> This is the description I used on the YouTube video itself, if we want to just reuse that

Great, just pushed a commit to add it, slightly modified. And as an added bonus, I was able to force push the reversion of changes I mentioned in https://github.com/farmOS/farmOS-community-blog/issues/5#issuecomment-1310872436, and the build hook worked:

https://source-farmos-community-blog--gracious-brattain-bdd606.netlify.app/blog/2022/farmos-in-5-minutes-video

**Review by jgaehring — APPROVED** [review]

**Comment by jgaehring** [comment]
Sorry I didn't realize I dismissed Paul's approval somehow, but presumably this is still ready to be merged, if @mstenta is ready to go ahead with it.

**Review by symbioquine — APPROVED** [review]

**Pull request merged**
